apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-03-14T19:48:59Z
  labels:
    run: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: "{{ .Release.Name }}"
  namespace: default
  resourceVersion: "117085"
  selfLink: /api/v1/namespaces/default/services/example
  uid: 35e432c6-4692-11e9-8d47-42010a9e0010
spec:
  ports:
  - nodePort: {{ .Values.service.externalPort }}
    port: {{ .Values.service.internalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    run: "{{ .Release.Name }}"
  sessionAffinity: None
  type: "{{ .Values.service.type }}"
status:
  loadBalancer: {}
